// lib/content/regional-semifinals-source.ts
//
// GENERATED FILE — do not edit by hand. Regenerate with: npm run refresh:semifinals
// (scripts/pull-regional-semifinals.mjs pulls the GESAwards Airtable base appyTu8uOPQUVXD4x
// and rewrites this file, then re-downloads logos and rebuilds regionalSemifinals.ts.)
//
// Sources:
// - Table "Partners" (tblAfv3rYs6GyXQEF): partner name + linked countries + logo attachment.
// - Table "all countries" (tbl7wFk8g0AbGx7ee): each country's real "Geographic Area".
// Last refreshed: 2026-07-15.

export type RawPartner = {
  /** Canonicalized Airtable record name. */
  name: string;
  /** Country names as linked in Airtable (US states not yet deduped). */
  countries: string[];
  /** Airtable attachment URL for the Logo field, if an image was uploaded. Expires —
   * scripts/download-partner-logos.mjs mirrors it locally. */
  logoUrl?: string;
};

export const RAW_PARTNERS: RawPartner[] = [
  {
    name: "Afinef",
    countries: [
      "France",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/I4QzJueSpjBawax4lBM-Lg/KwOjy6TCB0Da8U4qnVG1wGekbAx3YgHdxD4FIuamJeDz8JaneiqXV1gMT_izrpHqJDl9QzH5pPXE48F6fEJg9EK56UI72v3fNDAFWmNEBOURiPrRcR9Zt4SqhzHAjVYz5gSnlw4DoD9fKaDHdzDIdwE1aha4BUd1yLR98cevAwY/mBYVmyPtwNpaGKRPsA3BbDrISuqyJATGFf_UNp2evlY",
  },
  {
    name: "BR Founder Institute/ SchoolGuardian",
    countries: [
      "Brazil",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/Fs558ScfYNlGdm1eluOkOA/iksVzJ_4RMFKNKPFGxSFgf0DfwINhjpzsyjLCpI0lfky5UsRLFr495W9i-nktRUzd_iRGYdH0Z-tQMQzs0dZYYPnq2Fq5u8AkKf2iXKq3JJHPAfrTZkcRnaTfZnitzij_TGMVhSS_DumjNqR3_waMg/VB02VpGZjLRLtVLLYyoHTkc3TX4JNiZosYK-ebzDtjk",
  },
  {
    name: "DOHE",
    countries: [
      "Albania", "Belgium", "Croatia", "Cyprus", "Czech Republic", "Greece", "Hungary",
      "Malta", "Moldova", "Monaco", "Serbia", "Slovenia", "Switzerland", "Turkey", "Ukraine",
      "Andorra", "Belarus", "Bosnia and Herzegovina", "Bulgaria", "Kosovo", "Liechtenstein",
      "Luxembourg", "Macedonia (FYROM)", "Montenegro", "Netherlands", "Poland", "Romania",
      "San Marino", "Slovakia", "France", "Austria", "Germany", "Italy", "Spain",
      "United Kingdom (UK)",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/2iSDvAYVhemRZB8QLW6psw/bHT7v6WNnCcYdW9-jjC5EKGHt9JcP-VnxQhRjNJlTHm0EGAXBhETfvevBgSxRdOhYYPnw9an7ARq4m26yBvXu4CXPdLaWWIK69RKeGGUi3NADgI6O59Y5uNE8NN7rJwY6exVbyHTLjDTErdBYVLY97qRSeFPiH_VtgsjKW5qgig/WoiPEc8wfap2FhCnhrNHLG2VwnsAI9LJWAq3VGuXCeA",
  },
  {
    name: "Dutch EdTech",
    countries: [
      "Netherlands",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/saSR-_IU1ZJUJxDSphRuvA/8zEqSTxiSWVanxqNOHnLQc6ribOzLap4C-tHlpycjZkXoiCg2ojAcYu0KMnsB29SEY47xqA7OjZhsh_kEATENqwMyGzP4eiHjQqbJ77DlG8fj1w9lKeD_-bzJ4dSaLccAeFgQjo4VRE9VeIAwcYLRA/1Ua2BpC4NzfiLtwqCx6tPLb-rjr9UZo4rvue6XV1Ku4",
  },
  {
    name: "Edcrunch",
    countries: [
      "Russia", "Azerbaijan", "Kazakhstan", "Armenia", "Kyrgyzstan", "Uzbekistan",
      "Tajikistan", "Turkmenistan", "Mongolia", "Georgia",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/3wMATFg3kjc78Rfcc4RIyQ/X5r-OSJPk0fQszVcuFZmAirDjtUZRUmRO9BrVxV_uDZjSGWrUGQ7m8VrM2dKQOgve-13z4AuwAuLc24b5E7Y-FLUBAudSS8g3xR1d2V0ouowXQrKAeTuGiJwkLxejdeWc16s8ecxGHT9Wxa1oURXhw/ZcVMIgwdmtaezBVRfCM077SZpMxmsYzFhvt-xP211TQ",
  },
  {
    name: "EdLATAM Alliance",
    countries: [
      "Argentina", "Peru", "Chile", "Colombia", "Uruguay", "Paraguay", "Bolivia", "Ecuador",
      "Guyana", "Suriname", "Venezuela", "Belize", "Costa Rica", "El Salvador", "Guatemala",
      "Honduras", "Mexico", "Nicaragua", "Panama", "Cuba", "Dominican Republic", "Haiti",
      "Jamaica", "Bahamas", "Barbados", "Trinidad and Tobago",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/ER8xvPBWHzszGq4rx4-JYg/mdgQh1_jmtNqBZ3IZf5MyPeDNHdldkBZ_VkfLOoBX3EdSoCaoChz0fq0CsT5ZxThs4Vrr3Tjmv19bLxlZjzqyU4ke1NShoa4piYPGA7U8H4BOlP0qUQshH79cn84C9gBRUoP16TvRCdwKRFFeQPBFA/iGh42eZgZzfIqZR-uSU6_bQG20vodprTZSOszV0Xv_Q",
  },
  {
    name: "EdTech Austria - Innovation Salzburg",
    countries: [
      "Austria",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/rLCtWwfuQi_8BAE_0988BA/9Z56VrMepjjuPIWpCWwvo1bafHpEVDuLGcp3LDrVbnTiX7Cp5B2uEoFCsxpXzkls_0iVwVEz9xz3CCXlCKVVS7kXbCGx_wsYicWWwTZYmzrqvpWEvU9IR-KfacqliY990CUUZ1n1JpVBSD2yYZ5CWg/4PpPpnysjfDTbvNEc4wM38ixUWUbzEW6mwbiTjAyhHU",
  },
  {
    name: "EdTech France",
    countries: [
      "France",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/tdcu7xGLJqfBDL4vvwNVYA/ktUn9kWS6i79yKQBwX8LXlDFRkeE5IC5yHl6jat_6UAx2rM0vBlCu8LdMtTKl1rtcVjsvy9BLaOJFx6Az3jrzE1jtjJ0kc_NvDc_1_fLBypRWasqagBwYVF7VEOM85foQhbEuYBYO1FD0gDINVeyXAuq6q_qstBa6NwFamj2AxQ/Fc6Yg08AE-hPXR9x6M7gPu9bowIFv09jt6g-YMf00gE",
  },
  {
    name: "EdTech Italy",
    countries: [
      "Italy",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/uPP1Plum_fQ4vSWy3zga4w/rtq1yPXeC0VCI24JiqcCPBVliwKJX5_umAcFQlskMdh1hRHmmLNwuDJwCGJClkl52gZ-LogZtUdy8acg0HKynZuX-13uOfoUHoVFVUWtMiSNPRWHeEEZSDgqWyrqrr8jjWEYaF-f10aqiR1QfHlX2w/YFt4QDeFATe0ZctEphnfBK-8rzjzvVDYzGpdS1vnP7w",
  },
  {
    name: "Eduspaze",
    countries: [
      "Singapore", "Brunei", "Cambodia", "Indonesia", "Laos", "Malaysia", "Philippines",
      "Thailand", "East Timor", "Vietnam", "Myanmar (formerly Burma)",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/BMByf4keAOmOOtfqorkIgw/92L8Dww2e40xYjWi8hFxSyiipEL-Mo5a4sWO7Jpit1HPJTV5Xn4hhnN3Gt0IENlqpJYE_qGjtBDhLNJSuuS-j65WCY4_JVMw0Mm5RC3_bWs4kq4YHir0IpF16V9MaENMy6PWyj8ilT0oZLSWvyC7iQ/ZYBrbqrUexX25OBz0fI8-BedQ6KOxGEA65epskmxzLg",
  },
  {
    name: "Eduvation",
    countries: [
      "Germany",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/DHUjKnUi52_qQCwNUTdtBw/xqFGgoS39xbtb3-0CFPkWdmlS7YMzZoM9dwfVefZ36hMwJB9EJhNFagYzwjBeGiAivFmILRMao5MkNZ88g0jOk8_0ZjT3L4Sw3tXlpWsi-jRzDWWBCzA71Oy5jFXR9cM-d61O7m4OSIGuJ9U4xbfhtdeZSHZAaBgKanr0vB1Lfk/Wc1-WZbUeAxzMis2qOykbq7eU17JzpJV67pVTj1aun0",
  },
  {
    name: "Esperanza",
    countries: [
      "Hong Kong", "China",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/Nq0MZimaVc1kp3OPbR_hKA/LFO6bvo1_XTBfzLxXfO6Cl7eBxRp1NUcbLHbPaT0Mus4Y3HvYkbdgL-9rqOUxNJx1z9mzUseQVBUYympm7FJwiYXsgdBbimYU0Kfu8dyfQWf-Kb6EkbJr27ncn8xhHj1oRGYftHYmstuuSfWezTYVQ/MBLGkruUfutu1Jt5faA5jQ6UO2kva_S6NOAL0L41rtY",
  },
  {
    name: "GSET Ghana Society for Education Technology",
    countries: [
      "Nigeria", "Ethiopia", "Egypt", "Democratic Republic of the Congo",
      "Republic of the Congo", "Tanzania", "South Africa", "Kenya", "Sudan", "Uganda",
      "Algeria", "Morocco", "Angola", "Ghana", "Mozambique", "Madagascar", "Ivory Coast",
      "Cameroon", "Niger", "Mali", "Burkina Faso", "Malawi", "Zambia", "Chad", "Somalia",
      "Senegal", "Zimbabwe", "Guinea", "Benin", "Rwanda", "Burundi", "Tunisia", "South Sudan",
      "Togo", "Sierra Leone", "Libya", "Liberia", "Central African Republic (CAR)",
      "Mauritania", "Eritrea", "Namibia", "Gambia", "Gabon", "Botswana", "Lesotho",
      "Guinea-Bissau", "Equatorial Guinea", "Mauritius", "Eswatini", "Djibouti", "Comoros",
      "Cape Verde", "Sao Tome and Principe", "Seychelles",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/yUVrQjXcTfMEb3bf4Z2YUg/WjxF6XgRlItqauMwUfR_muEExZMfh3WGyZ2j0mS8q5jrct2G98-OvF1FXRMhVEKGpBjLXWgzZyr7tTGSa0g3ASt10YV3PDJ9nTjBGHtDCACK5fWamyQQI58iGS6KNyEAnBcFkd5phmKDZfq-IIZtHw/JBkdphkrvEnagCzDgQKMMFL-3dPqZrCVhXxLDL7H4yw",
  },
  {
    name: "Ingenious Faces",
    countries: [
      "India",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/kpjUErYCyAAyPj4087g09Q/1zFoca7LhFlc_3-wMW8c_kDgmp1vtJmvg4nSSrar3ov8WCmPqvdHq1KYMuO-GNg498PtrMLt8qCmko_Bgkul_JvJYrPzqbOEPj73yLgHt55kLNSfstlt0Huhw1BtQXEQAcNCbDQgAdNrg8tH20XveA/4kiDAvLPA756RpSXzFGla8nfOylcn6HKw2cI6du5yDQ",
  },
  {
    name: "Learning Spark",
    countries: [
      "South Korea", "North Korea",
    ],
  },
  {
    name: "Learnlaunch",
    countries: [
      "USA - Alabama", "USA - Arkansas", "USA - Illinois", "USA - New Jersey",
      "USA - Pennsylvania", "USA - Washington D.C", "Canada",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/TCpxHckfIDjVeWwdwqe-Kw/0wNzEwpWwbzT9vkEOBsQnFeTUfmxTXTuGoNEAjDdYPPnheGaHMd4p4lT6oeoLbVbOuoaQvuGpPvQQl0KiR1wbummSRjOnr-DiuEAqTts6q4GRTemRsHe8ARdOBYJ6bbM_kpt8RmTp5h6WNkmhvgTFQLF4U7xOukw7-ytb4fz_Zw/BOEWtmcDAltRk5c6WsDVWnMgDNZxSlOlBu7EzWgWNAo",
  },
  {
    name: "METI Japan",
    countries: [
      "Japan",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/ivZYUgifwXLRX68JRNNAxQ/EOk21fkuvoVkfdbZGAf4tfsOQmU4Jr3-A7juW3BdNv0AZDCpMrux9IrpuuREfmSPQFmuAS5eKEG5Iu6a_sTMfT0uqbTym2tKBeheloi3FkIGXdVS2pfj0z_PGtW_bceTTmpqmeoVGE6lxqnCblkZVw/pqV4ahIh89GfCvz-YZul8OhjK8c2TN9OOjJU-oA1C9I",
  },
  {
    name: "Positivo",
    countries: [
      "Brazil",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/qWYYMp0TCrVjaNWrwFnUnA/wX5b3SrNok9l89iKXBoUFQ7RxHiotOCe-nyodb7mukI5sQKdAtZe7NQ-d-QbieNGs2zFH1C74C9kRabo-OEjsUixUO38FJy0ENOHIL86uuFbRA0LMQj69yzosykpNmdnIar4vKlhUBqrwiGGA0DFpw/fnU5k2dgRiVvV94ddC7-LxVzlZ7A1biWxekFkCOdK3M",
  },
  {
    name: "Prismapar",
    countries: [
      "Argentina", "Peru", "Chile", "Colombia", "Uruguay", "Paraguay", "Bolivia",
      "Equatorial Guinea", "Ecuador", "Guyana", "Suriname", "Venezuela", "Belize",
      "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Mexico", "Nicaragua", "Panama",
      "Cuba", "Dominican Republic", "Haiti", "Jamaica", "Bahamas", "Barbados",
      "Trinidad and Tobago",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/y0NAhL1mvSCnwgzOQyxoxg/6W9uqarYBakPIX4NDNZ00Jx443izXdKMx_dfwaBNxflZfL1YygmTIx8yPIpBYX2mnGWkRli2HpEvvoWIDR7FWK_L_1rpo8rvem1ves-Pn1THi4sM5wIGLdw2H5-Er_nFNhbt1E_-V6lcMb9KGJPmyg/cXqiTRBFBiDoQMbxPvT8r63GLIREriedahlFJKvL3L4",
  },
  {
    name: "SEK Lab",
    countries: [
      "Portugal", "Spain",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/UH-bdUJ9jkRYfcQeEGdP7w/IZiIIJFHWPTKWp3pNw1yobqZ-P6BvB3FvWLokhgpW1EeK53M1lH8ERBDUqle7DN-Lrnpg2LlTGkksJwCQ9MQoFDjYfjmb2vYA0xja0DPbkt2GA09yF4xaYvm3IbMdknQbKwYxuTXneQ6aYlUS-nfCw/pTVtobuQrLnGtOei4xZyooLt3kq4-idAh5A-SadDSNQ",
  },
  {
    name: "StartEdAccelerator",
    countries: [
      "USA - Alaska", "USA - Arizona", "USA - California", "USA - Colorado", "USA - Montana",
      "USA - Wyoming",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/LiyXZtrb_JOHX1AzJaEqHA/KL3-iBo_5oxflaUykE1-qE-uxVEdDW4sgPCDhpzC-DLsTvkXRNC7H-tl7KZEAtgha-Mni39Y5Mp6n17mfz_kUI2W7Pn_vIthBUwyCiFz5SVybYSuUlx4c7P38pmX5Bk9d636i9DM-a5TDiSJsrejBA/ydZBxKy32jEzWnK-Vejb6ycCztDLUc3s4NLesreXgW0",
  },
  {
    name: "Startup Braga",
    countries: [
      "Portugal",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/unUHGUOyJCd0E5PU_De8Bw/CJRIWKHKnx73_Gfl7iqTZaHlJVD1pofZYM0TDjfQBlkvfHsfUF7bubkNvVx8mQpKO6rTgKTV8tC2OWLdX1cs6Gf5V7YFQg2diLqjhWKAs6o1kCmvmVoSnuyxkDeQes-ATprQdDfnfLr1f5uE3ttO8Q/40VKne_vVxen0dL0c-GoWWHc65C02CJgJrxoHhXiA3s",
  },
  {
    name: "Taipei Computer Association (TCA)",
    countries: [
      "Taiwan",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/GdsntSujwAHJsfl6D_-Z2Q/21xU-QtiPnvWTXmyRd4_baHlToKNF4QdzkH_dE7MMs8_8MSPukELXJ-5L0O5SOJ2REMItch02trGsDi-QCsA4bjsgI8zcU3eeNjyby3KjS9YRKY_1dcS3mRkBEYDcCuwNuKQEp89tRpgGm4QIu9lru2qSTg8n6MgYr5JaXH7TuM/Bj5SSEY7nJAragFsYVLG7oE3Lemh73dJNAh5_bwt3i4",
  },
  {
    name: "Tech Monterrey",
    countries: [
      "Argentina", "Peru", "Chile", "Colombia", "Uruguay", "Paraguay", "Bolivia",
      "Equatorial Guinea", "Ecuador", "Guyana", "Suriname", "Venezuela", "Belize",
      "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Mexico", "Nicaragua", "Panama",
      "Cuba", "Dominican Republic", "Haiti", "Jamaica", "Bahamas", "Barbados",
      "Trinidad and Tobago",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/Aq-R3sidB9Rt7nHaWvBefA/iWQ4zaBlJBtosWdZCCt1SA4DmtTHf8jTkpCVGnQGyF5mSGJn_sIvTxAXhmBorhzm2Q_2ItwIpxWwI4hA6Z8wSv1Ct6WK7-BbuUdwulYS0B_NJOYHr8TqAkzYEbGV6E1AVm9oHC4xi4S10IgwoHtaRtgt7CehXx9eC6A6sooUKqM/_UzSiD4RC8BcTYDS6Lv0vtHTPVCy_ik6AgqCwHyIROg",
  },
  {
    name: "Tyme Education",
    countries: [
      "Australia", "Bangladesh", "Iraq", "Jordan", "Kuwait", "Lebanon", "Nepal", "Pakistan",
      "Papua New Guinea", "Saudi Arabia", "United Arab Emirates (UAE)",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/Vwpe5TdmoH1girfkBh3emw/sjua8EPKwdc9ks94OypANeHjmhYsZiktEBXLTMPodcotSiEQk5Y-5JSWMiazAK63vS-JeKdbBfo48c-RFTeqSmascF6ieAQrSBOZ7AjxxWYgqmrLGkXsodBUpCRXXJhuRyoSwdpKCUc8XUpZ_9zFDAcS9d52lqHe9izae2Cv9YM/KTp-e3QpE8pTlMy5U25QWGzNevG8gs0KM_baDT0tPbM",
  },
  {
    name: "UCL EdTech Labs",
    countries: [
      "United Kingdom (UK)",
    ],
  },
  {
    name: "XEdu",
    countries: [
      "Denmark", "Sweden", "Estonia", "Finland", "Iceland", "Latvia", "Lithuania", "Norway",
    ],
    logoUrl:
      "https://v5.airtableusercontent.com/v3/u/55/55/1784131200000/G06_FnUADQGncd-lSeNtsw/ko-eXUKbHijEOFsa-Z7t0AA-tvByCpyi9PAu_fDApflkxjqxCEGbz0T5ykk6CmPDXrY0DU593K8lnnFVYMhObheH23r6F7txq7RmhUGesP99b3KKgDvG9YIrx9WYenZe28WQ69UtQi2ZFJdWaFKBqA/-yGuUXllK7tTQ2iwpf7GCIdcp8JlXV9B0sTehZBOTS0",
  },
];

/**
 * "Geographic Area" from Airtable's "all countries" table, keyed by country name after
 * US-state collapsing. Countries without an area in Airtable (mainly Hong Kong) default
 * to "rest-of-world".
 */
export const COUNTRY_TO_CONTINENT: Record<string, ContinentKeyRaw> = {
  "Albania": "europe",
  "Algeria": "africa",
  "Andorra": "europe",
  "Angola": "africa",
  "Argentina": "latin-america",
  "Armenia": "asia",
  "Australia": "rest-of-world",
  "Austria": "europe",
  "Azerbaijan": "asia",
  "Bahamas": "latin-america",
  "Bangladesh": "rest-of-world",
  "Barbados": "latin-america",
  "Belarus": "europe",
  "Belgium": "europe",
  "Belize": "latin-america",
  "Benin": "africa",
  "Bolivia": "latin-america",
  "Bosnia and Herzegovina": "europe",
  "Botswana": "africa",
  "Brazil": "latin-america",
  "Brunei": "asia",
  "Bulgaria": "europe",
  "Burkina Faso": "africa",
  "Burundi": "africa",
  "Cambodia": "asia",
  "Cameroon": "africa",
  "Canada": "north-america",
  "Cape Verde": "africa",
  "Central African Republic (CAR)": "africa",
  "Chad": "africa",
  "Chile": "latin-america",
  "China": "asia",
  "Colombia": "latin-america",
  "Comoros": "africa",
  "Costa Rica": "latin-america",
  "Croatia": "europe",
  "Cuba": "latin-america",
  "Cyprus": "europe",
  "Czech Republic": "europe",
  "Democratic Republic of the Congo": "africa",
  "Denmark": "europe",
  "Djibouti": "africa",
  "Dominican Republic": "latin-america",
  "East Timor": "asia",
  "Ecuador": "latin-america",
  "Egypt": "middle-east",
  "El Salvador": "latin-america",
  "Equatorial Guinea": "africa",
  "Eritrea": "africa",
  "Estonia": "europe",
  "Eswatini": "africa",
  "Ethiopia": "africa",
  "Finland": "europe",
  "France": "europe",
  "Gabon": "africa",
  "Gambia": "africa",
  "Georgia": "asia",
  "Germany": "europe",
  "Ghana": "africa",
  "Greece": "europe",
  "Guatemala": "latin-america",
  "Guinea": "africa",
  "Guinea-Bissau": "africa",
  "Guyana": "latin-america",
  "Haiti": "latin-america",
  "Honduras": "latin-america",
  "Hong Kong": "rest-of-world",
  "Hungary": "europe",
  "Iceland": "europe",
  "India": "asia",
  "Indonesia": "asia",
  "Iraq": "middle-east",
  "Italy": "europe",
  "Ivory Coast": "africa",
  "Jamaica": "latin-america",
  "Japan": "asia",
  "Jordan": "middle-east",
  "Kazakhstan": "asia",
  "Kenya": "africa",
  "Kosovo": "europe",
  "Kuwait": "middle-east",
  "Kyrgyzstan": "asia",
  "Laos": "asia",
  "Latvia": "europe",
  "Lebanon": "middle-east",
  "Lesotho": "africa",
  "Liberia": "africa",
  "Libya": "africa",
  "Liechtenstein": "europe",
  "Lithuania": "europe",
  "Luxembourg": "europe",
  "Macedonia (FYROM)": "europe",
  "Madagascar": "africa",
  "Malawi": "africa",
  "Malaysia": "asia",
  "Mali": "africa",
  "Malta": "europe",
  "Mauritania": "africa",
  "Mauritius": "africa",
  "Mexico": "latin-america",
  "Moldova": "europe",
  "Monaco": "europe",
  "Mongolia": "asia",
  "Montenegro": "europe",
  "Morocco": "africa",
  "Mozambique": "africa",
  "Myanmar (formerly Burma)": "asia",
  "Namibia": "africa",
  "Nepal": "rest-of-world",
  "Netherlands": "europe",
  "Nicaragua": "latin-america",
  "Niger": "africa",
  "Nigeria": "africa",
  "North Korea": "rest-of-world",
  "Norway": "europe",
  "Pakistan": "rest-of-world",
  "Panama": "latin-america",
  "Papua New Guinea": "rest-of-world",
  "Paraguay": "latin-america",
  "Peru": "latin-america",
  "Philippines": "asia",
  "Poland": "europe",
  "Portugal": "europe",
  "Republic of the Congo": "africa",
  "Romania": "europe",
  "Russia": "europe",
  "Rwanda": "africa",
  "San Marino": "europe",
  "Sao Tome and Principe": "africa",
  "Saudi Arabia": "middle-east",
  "Senegal": "africa",
  "Serbia": "europe",
  "Seychelles": "africa",
  "Sierra Leone": "africa",
  "Singapore": "asia",
  "Slovakia": "europe",
  "Slovenia": "europe",
  "Somalia": "africa",
  "South Africa": "africa",
  "South Korea": "asia",
  "South Sudan": "africa",
  "Spain": "europe",
  "Sudan": "africa",
  "Suriname": "latin-america",
  "Sweden": "europe",
  "Switzerland": "europe",
  "Taiwan": "rest-of-world",
  "Tajikistan": "asia",
  "Tanzania": "africa",
  "Thailand": "asia",
  "Togo": "africa",
  "Trinidad and Tobago": "latin-america",
  "Tunisia": "africa",
  "Turkey": "middle-east",
  "Turkmenistan": "rest-of-world",
  "Uganda": "africa",
  "Ukraine": "europe",
  "United Arab Emirates (UAE)": "middle-east",
  "United Kingdom (UK)": "europe",
  "United States": "north-america",
  "Uruguay": "latin-america",
  "Uzbekistan": "asia",
  "Venezuela": "latin-america",
  "Vietnam": "asia",
  "Zambia": "africa",
  "Zimbabwe": "africa",
};
type ContinentKeyRaw =
  | "europe" | "asia" | "middle-east" | "north-america"
  | "latin-america" | "africa" | "rest-of-world";

/**
 * ISO 3166-1 alpha-2 (lowercase) for every country name used above, after US-state
 * collapsing. flag-icons keys its classes by this code (e.g. "fi-us").
 * Maintained in scripts/pull-regional-semifinals.mjs — add new codes there.
 */
export const COUNTRY_TO_ISO2: Record<string, string> = {
  "Albania": "al",
  "Algeria": "dz",
  "Andorra": "ad",
  "Angola": "ao",
  "Argentina": "ar",
  "Armenia": "am",
  "Australia": "au",
  "Austria": "at",
  "Azerbaijan": "az",
  "Bahamas": "bs",
  "Bangladesh": "bd",
  "Barbados": "bb",
  "Belarus": "by",
  "Belgium": "be",
  "Belize": "bz",
  "Benin": "bj",
  "Bolivia": "bo",
  "Bosnia and Herzegovina": "ba",
  "Botswana": "bw",
  "Brazil": "br",
  "Brunei": "bn",
  "Bulgaria": "bg",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cambodia": "kh",
  "Cameroon": "cm",
  "Canada": "ca",
  "Cape Verde": "cv",
  "Central African Republic (CAR)": "cf",
  "Chad": "td",
  "Chile": "cl",
  "China": "cn",
  "Colombia": "co",
  "Comoros": "km",
  "Costa Rica": "cr",
  "Croatia": "hr",
  "Cuba": "cu",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Democratic Republic of the Congo": "cd",
  "Denmark": "dk",
  "Djibouti": "dj",
  "Dominican Republic": "do",
  "East Timor": "tl",
  "Ecuador": "ec",
  "Egypt": "eg",
  "El Salvador": "sv",
  "Equatorial Guinea": "gq",
  "Eritrea": "er",
  "Estonia": "ee",
  "Eswatini": "sz",
  "Ethiopia": "et",
  "Finland": "fi",
  "France": "fr",
  "Gabon": "ga",
  "Gambia": "gm",
  "Georgia": "ge",
  "Germany": "de",
  "Ghana": "gh",
  "Greece": "gr",
  "Guatemala": "gt",
  "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Guyana": "gy",
  "Haiti": "ht",
  "Honduras": "hn",
  "Hong Kong": "hk",
  "Hungary": "hu",
  "Iceland": "is",
  "India": "in",
  "Indonesia": "id",
  "Iraq": "iq",
  "Italy": "it",
  "Ivory Coast": "ci",
  "Jamaica": "jm",
  "Japan": "jp",
  "Jordan": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Kosovo": "xk",
  "Kuwait": "kw",
  "Kyrgyzstan": "kg",
  "Laos": "la",
  "Latvia": "lv",
  "Lebanon": "lb",
  "Lesotho": "ls",
  "Liberia": "lr",
  "Libya": "ly",
  "Liechtenstein": "li",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Macedonia (FYROM)": "mk",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Malaysia": "my",
  "Mali": "ml",
  "Malta": "mt",
  "Mauritania": "mr",
  "Mauritius": "mu",
  "Mexico": "mx",
  "Moldova": "md",
  "Monaco": "mc",
  "Mongolia": "mn",
  "Montenegro": "me",
  "Morocco": "ma",
  "Mozambique": "mz",
  "Myanmar (formerly Burma)": "mm",
  "Namibia": "na",
  "Nepal": "np",
  "Netherlands": "nl",
  "Nicaragua": "ni",
  "Niger": "ne",
  "Nigeria": "ng",
  "North Korea": "kp",
  "Norway": "no",
  "Pakistan": "pk",
  "Panama": "pa",
  "Papua New Guinea": "pg",
  "Paraguay": "py",
  "Peru": "pe",
  "Philippines": "ph",
  "Poland": "pl",
  "Portugal": "pt",
  "Republic of the Congo": "cg",
  "Romania": "ro",
  "Russia": "ru",
  "Rwanda": "rw",
  "San Marino": "sm",
  "Sao Tome and Principe": "st",
  "Saudi Arabia": "sa",
  "Senegal": "sn",
  "Serbia": "rs",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Singapore": "sg",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Somalia": "so",
  "South Africa": "za",
  "South Korea": "kr",
  "South Sudan": "ss",
  "Spain": "es",
  "Sudan": "sd",
  "Suriname": "sr",
  "Sweden": "se",
  "Switzerland": "ch",
  "Taiwan": "tw",
  "Tajikistan": "tj",
  "Tanzania": "tz",
  "Thailand": "th",
  "Togo": "tg",
  "Trinidad and Tobago": "tt",
  "Tunisia": "tn",
  "Turkey": "tr",
  "Turkmenistan": "tm",
  "Uganda": "ug",
  "Ukraine": "ua",
  "United Arab Emirates (UAE)": "ae",
  "United Kingdom (UK)": "gb",
  "United States": "us",
  "Uruguay": "uy",
  "Uzbekistan": "uz",
  "Venezuela": "ve",
  "Vietnam": "vn",
  "Zambia": "zm",
  "Zimbabwe": "zw",
};
