import json
from pathlib import Path
from collections import defaultdict

# Load graph and analysis
graph = json.loads(Path('graphify-out/graph.json').read_text(encoding='utf-8'))
analysis = json.loads(Path('graphify-out/.graphify_analysis.json').read_text(encoding='utf-8'))
detect = json.loads(Path('graphify-out/.graphify_detect.json').read_text(encoding='utf-8'))

# Extract god nodes and surprising connections
nodes = {n['id']: n for n in graph['nodes']}
communities = {int(k): set(v) for k, v in analysis.get('communities', {}).items()}

# Find influential nodes (high degree)
node_degree = defaultdict(int)
for link in graph.get('links', []):
    node_degree[link['source']] += 1
    node_degree[link['target']] += 1

god_nodes = sorted(node_degree.items(), key=lambda x: x[1], reverse=True)[:5]

# Community labels
labels = {}
for cid in sorted(communities.keys()):
    comm_nodes = list(communities[cid])[:3]
    node_names = [nodes.get(nid, {}).get('label', nid) for nid in comm_nodes]
    labels[cid] = ' / '.join(node_names[:2])

# Generate markdown report
report = f"""# Graph Report: gesa-website

## Overview
- **Nodes**: {len(graph['nodes'])}
- **Edges**: {len(graph.get('links', []))}
- **Communities**: {len(communities)}
- **Files analyzed**: {detect['total_files']} files ({detect['total_words']:,} words)

## God Nodes (Most Connected)

These are the most central components in your codebase:

"""

for node_id, degree in god_nodes:
    node_data = nodes.get(node_id, {})
    label = node_data.get('label', node_id)
    node_type = node_data.get('type', 'unknown')
    report += f"- **{label}** ({node_type}) — {degree} connections\n"

report += f"""
## Communities

Your codebase is organized into {len(communities)} communities:

"""

for cid in sorted(communities.keys()):
    comm_nodes = list(communities[cid])
    label = labels.get(cid, f'Community {cid}')
    report += f"- **Community {cid}**: {label}\n  ({len(comm_nodes)} nodes)\n"

report += f"""
## File Structure

Code files by category:
- TypeScript/JavaScript: {len([f for f in detect['files'].get('code', []) if f.endswith(('.ts', '.tsx', '.js', '.jsx'))])}
- Configuration: {len([f for f in detect['files'].get('code', []) if 'config' in f.lower() or f.endswith(('.json', '.yaml', '.yml'))])}
- Documentation: {detect['files'].get('document', []).__len__()}
- Images/Assets: {detect['files'].get('image', []).__len__()}

## Suggested Questions

- How do core components interact across boundaries?
- Which modules are tightly coupled?
- What are the most critical paths through the system?

## Visualization

Open `graph.html` in a browser to explore the interactive knowledge graph.

---

*Generated by graphify — a knowledge graph extraction tool*
"""

Path('graphify-out/GRAPH_REPORT.md').write_text(report, encoding='utf-8')
print("✓ Report generated: GRAPH_REPORT.md")
